/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.60.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.5
*/

export type { PetitionContractAbi } from './PetitionContractAbi';

export { PetitionContractAbi__factory } from './factories/PetitionContractAbi__factory';
